Bug: Domain only validation doesn't work for custom schemes
ProjectLibertyLabs/siwf pull request #205
Opened 2024-10-28 23:36 UTC by mattheworris

# Problem

Closes #200

2024-10-29 14:48 UTC, wilwade requested changes
Few fixes and questions, but I think the core validation logic is correct.

2024-10-29 14:48 UTC, wilwade commented on libraries/js/src/mocks/payloads.ts
> +  return `${domain} wants you to sign in with your Frequency account:\n${account}\n\n\n\nURI: ${uri}\nNonce: N6rLwqyz34oUxJEXJ\nIssued At: ${issued.toISOString()}\nExpiration Time: ${expires.toISOStr
```suggestion
function generateLoginMessage(account: string, issued: Date, expires: Date, uri: URL) {
  return `${uri.hostname} wants you to sign in with your Frequency account:\n${account}\n\n\n\nURI: ${uri}\nNonce: N6rLwqyz34oUxJEXJ\nIssued At: ${issued.toISOString()}\nExpiration Time: ${expires.toISOString()}`;
```

2024-10-29 14:48 UTC, wilwade commented on libraries/js/src/mocks/payloads.ts
>      domain
```suggestion
    new URL('https://your-app.com/signin/callback')
```

2024-10-29 14:48 UTC, wilwade commented on libraries/js/src/payloads.ts
> +  // SIWF_V2_DOMAIN may be configured with or without a scheme that accommodates app-specific needs.
`SIWF_V2_DOMAIN` is not known by this library.

2024-10-29 14:48 UTC, wilwade commented on libraries/js/src/payloads.ts
> +function validateDomain(msgDomain: string, expectedDomain: string) {
```suggestion
function validateDomainAndUri(msgUri: string, expectedUri: string) {
```

2024-10-29 14:56 UTC, mattheworris commented on libraries/js/src/payloads.ts
> +  validateDomain(msg.domain, loginMsgDomain);
Yes, my tests are off, working on updating now.

2024-10-30 18:41 UTC, mattheworris commented on libraries/js/src/mocks/payloads.ts
> +    encodedValue: u8aToHex(ExampleUserKey.keyPair().sign(loginMessageGood())),
domain will always match the URI in the test cases

2024-10-30 18:42 UTC, mattheworris commented on libraries/js/src/payloads.ts
> +/**
Added: helpful for hover over in IDE

2024-10-30 18:44 UTC, mattheworris commented on libraries/js/src/response.test.ts
> +      getLoginResult('fakeAuthCode', { loginMsgUri: 'testnet.frequencyaccess.com' })
`localhost` changed in `ExampleLogin()`

2024-10-30 21:10 UTC, JoeCap08055 reviewed
Hmm, I've lost quite a bit of context since SIWFv1, but I just want to point out that `domain` and `uri` are two separate and unrelated things in the "Sign in with Ethereum" (Sign in With X) spec.

`domain` is the domain of the app requesting a signin (ie, mewe.com)
`uri` is the URI of the signing app (ie, frequencyaccess.com)

We should make sure that our use of these fields is as the standard expects; at this point I'm a little unclear if it does.
(Realizing that this may work fine for SIWFv2, but may break when we re-integrate standalone wallets and/or the Talisman SIWS package)

2024-10-31 14:10 UTC, JoeCap08055 approved these changes
My comments/concerns addressed in an external thread; looks good!

2024-10-31 14:39 UTC, wilwade commented on docs/src/Actions/Response.md
> +Inside the message, `{{domain}}` is the domain of the application requesting the sign-in. `{{domain}}` should match the domain contained in the `URI` field.
❤️

2024-10-31 14:40 UTC, mattheworris commented on docs/src/Actions/Response.md
> +Inside the message, `{{domain}}` is the domain of the application requesting the sign-in. `{{domain}}` should match the domain contained in the `URI` field.
Domain clarification

2024-10-31 15:02 UTC, wilwade approved these changes
💯 Thanks!

2024-10-31 15:08 UTC, merged